version: "3.8"

services:
    milatiparis:
        build:
            context: .
            args:
                - DOTENV_PRIVATE_KEY=${DOTENV_PRIVATE_KEY}
        restart: always
        environment:
            - NODE_ENV=production
            - DOTENV_PRIVATE_KEY=${DOTENV_PRIVATE_KEY}
            - NEXTAUTH_URL=https://assistant.milatiparis.com
        networks:
            - my_shared_network
        labels:
            - traefik.enable=true
            - traefik.http.routers.milatiparis.rule=Host(`assistant.milatiparis.com`)
            - traefik.http.routers.milatiparis.tls=true
            - traefik.http.routers.milatiparis.entrypoints=web,websecure
            - traefik.http.routers.milatiparis.tls.certresolver=mytlschallenge
            - traefik.http.middlewares.milatiparis.headers.SSLRedirect=true
            - traefik.http.middlewares.milatiparis.headers.STSSeconds=315360000
            - traefik.http.middlewares.milatiparis.headers.browserXSSFilter=true
            - traefik.http.middlewares.milatiparis.headers.contentTypeNosniff=true
            - traefik.http.middlewares.milatiparis.headers.forceSTSHeader=true
            - traefik.http.middlewares.milatiparis.headers.SSLHost=assistant.milatiparis.com
            - traefik.http.middlewares.milatiparis.headers.STSIncludeSubdomains=true
            - traefik.http.middlewares.milatiparis.headers.STSPreload=true
            - traefik.http.routers.milatiparis.middlewares=milatiparis@docker
            - traefik.http.services.milatiparis.loadbalancer.server.port=3000

networks:
    my_shared_network:
        external: true
